name: "🚀 Feature Request"
description: "Suggest a new feature"
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Feature description"
      description: "What feature would you like to see?"
      placeholder: "Script syntax highlighting in the editor..."

  - type: textarea
    id: use_case
    attributes:
      label: "Use case"
      description: "Why is this useful? What problem does it solve?"
      placeholder: "This would allow faster debugging of complex scripts..."

  - type: textarea
    id: alternatives
    attributes:
      label: "Current workarounds"
      description: "What do you do right now?"
      placeholder: "I copy/paste code to VS Code for editing..."

  - type: textarea
    id: implementation
    attributes:
      label: "Implementation ideas (optional)"
      description: "Any thoughts on how this could be implemented?"
